<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="QLM Application Automation Test Suite" duration-ms="193817" started-at="2020-04-21T11:08:52Z" finished-at="2020-04-21T11:12:06Z">
    <groups>
    </groups>
    <test name="QLM Application Test Case3" duration-ms="193817" started-at="2020-04-21T11:08:52Z" finished-at="2020-04-21T11:12:06Z">
      <class name="com.qlm.qa.testcases.AuditTemplateAmendPageTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qlm.qa.testcases.AuditTemplateAmendPageTest@50b494a6]" name="setUp" is-config="true" duration-ms="68352" started-at="2020-04-21T16:38:52Z" finished-at="2020-04-21T16:40:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="validateAuditTemplateAmendPageTitleTest()[pri:1, instance:com.qlm.qa.testcases.AuditTemplateAmendPageTest@50b494a6]" name="validateAuditTemplateAmendPageTitleTest" duration-ms="20" started-at="2020-04-21T16:40:00Z" finished-at="2020-04-21T16:40:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateAuditTemplateAmendPageTitleTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qlm.qa.testcases.AuditTemplateAmendPageTest@50b494a6]" name="tearDown" is-config="true" duration-ms="1003" started-at="2020-04-21T16:40:00Z" finished-at="2020-04-21T16:40:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qlm.qa.testcases.AuditTemplateAmendPageTest@50b494a6]" name="setUp" is-config="true" duration-ms="56775" started-at="2020-04-21T16:40:01Z" finished-at="2020-04-21T16:40:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="SKIP" signature="validateSubmitAuditTemplateTest()[pri:2, instance:com.qlm.qa.testcases.AuditTemplateAmendPageTest@50b494a6]" name="validateSubmitAuditTemplateTest" duration-ms="3" started-at="2020-04-21T16:40:58Z" finished-at="2020-04-21T16:40:58Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:304)
	at org.testng.Assert.assertEquals(Assert.java:314)
	at com.qlm.qa.testcases.AuditTemplateAmendPageTest.validateSubmitAuditTemplateTest(AuditTemplateAmendPageTest.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateSubmitAuditTemplateTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qlm.qa.testcases.AuditTemplateAmendPageTest@50b494a6]" name="tearDown" is-config="true" duration-ms="919" started-at="2020-04-21T16:40:58Z" finished-at="2020-04-21T16:40:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qlm.qa.testcases.AuditTemplateAmendPageTest@50b494a6]" name="setUp" is-config="true" duration-ms="64082" started-at="2020-04-21T16:40:59Z" finished-at="2020-04-21T16:42:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="validateSubmitAuditTemplateTest()[pri:2, instance:com.qlm.qa.testcases.AuditTemplateAmendPageTest@50b494a6]" name="validateSubmitAuditTemplateTest" duration-ms="1" started-at="2020-04-21T16:42:03Z" finished-at="2020-04-21T16:42:03Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:304)
	at org.testng.Assert.assertEquals(Assert.java:314)
	at com.qlm.qa.testcases.AuditTemplateAmendPageTest.validateSubmitAuditTemplateTest(AuditTemplateAmendPageTest.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateSubmitAuditTemplateTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qlm.qa.testcases.AuditTemplateAmendPageTest@50b494a6]" name="tearDown" is-config="true" duration-ms="2235" started-at="2020-04-21T16:42:03Z" finished-at="2020-04-21T16:42:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.qlm.qa.testcases.AuditTemplateAmendPageTest -->
    </test> <!-- QLM Application Test Case3 -->
  </suite> <!-- QLM Application Automation Test Suite -->
</testng-results>
